### ISSUE TITLE
hostname option doesn't appear to be propagated to OneDHCPD

### ISSUE THREAD

**Issue by aadavids** [nerves-networking/vintage_net_direct#55]
**Describe the bug**
I've been trying to hardcode a hostname to use with VintageNetDirect so that the IP address of the DHCP server will be always be the same. The IP address is consistent when a hostname is hardcoded, but the IP address assigned to the client is on a different subnet.

**To Reproduce**
1. Connect target device directly to computer via Ethernet. Configure eth0 to a VintageNetDirect configuration.

```
ifname = "eth0"
hostname = "myHostname"
VintageNet.configure(ifname, %{type: VintageNetDirect, vintage_net_direct: %{hostname: hostname}}, persist: false)
```

The Ethernet IP address for the DHCP server should be 172.31.113.21/30. When I configure without a hostname, the Ethernet IP address for the DHCP server on my device is 172.31.245.133/30.

2. Check the IP address assigned to the computer's Ethernet port. The IP address is on the subnet that would have been used if no hostname was specified.  

```
$ ifconfig enx0050b6dd3496

enx0050b6dd3496: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.31.245.134  netmask 255.255.255.252  broadcast 172.31.245.135
        inet6 fe80::4f10:f7d9:c896:6015  prefixlen 64  scopeid 0x20<link>
        ether 00:50:b6:dd:34:96  txqueuelen 1000  (Ethernet)
        RX packets 718  bytes 70951 (70.9 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 427  bytes 73502 (73.5 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

3. In addition, if you check the state of the OneSHCPDServer, the IP addresses it's using match the IP address assigned to the client, not the IP address of the interface in VintageNet.

```
iex(41)> OneDHCPD.Server.server_name("eth0") |> :sys.get_state                                                                %OneDHCPD.Server.State{                  
  ifname: "eth0",
  our_ip_address: {172, 31, 245, 133},
  socket: #Port<0.1599>,
  subnet: {172, 31, 245, 132},
  subnet_mask: {255, 255, 255, 252},
  their_ip_address: {172, 31, 245, 134}
}
```

**Expected behavior**
OneDHCPD should assign IP addresses on the correct subnet. 

**VintageNet Info**

Output of `VintageNet.info` (please hide any sensitive information like WiFi PSKs)

```
iex(44)> VintageNet.info                                                                                                      
VintageNet 0.9.3               

All interfaces:       ["eth0", "eth0.1049", "lo", "usb0"]
Available interfaces: ["eth0.1049"]

Interface eth0
  Type: VintageNetDirect
  Present: true
  State: :configured (0:04:37)
  Connection: :lan (0:04:35)
  Addresses: fe80::f6e1:1eff:fece:f0ee/64, 172.31.113.21/30
  Configuration:
    %{type: VintageNetDirect, vintage_net_direct: %{hostname: "myHostname"}}

```

**Environment**

* Nerves environment: (`mix nerves.env --info`)
```
❯ mix nerves.env --info

==> nerves
==> brooklyn_nerves
|nerves_bootstrap| Environment Package List

  Pkg:         nerves_system_bkln
  Vsn:         2.9.0
  Type:        system
  BuildRunner: {Nerves.Artifact.BuildRunners.Local, []}

  Pkg:         nerves_system_br
  Vsn:         1.14.4
  Type:        system_platform
  BuildRunner: {nil, []}

  Pkg:         nerves_toolchain_armv7_nerves_linux_gnueabihf
  Vsn:         1.4.2
  Type:        toolchain
  BuildRunner: {Nerves.Artifact.BuildRunners.Local, []}

  Pkg:         nerves_toolchain_ctng
  Vsn:         1.8.3
  Type:        toolchain_platform
  BuildRunner: {nil, []}

|nerves_bootstrap| Loadpaths Start


Nerves environment
  MIX_TARGET:   bkln
  MIX_ENV:      dev

|nerves_bootstrap| Environment Variable List
  target:     bkln
  toolchain:  /home/andrew/.nerves/artifacts/nerves_toolchain_armv7_nerves_linux_gnueabihf-linux_x86_64-1.4.2
  system:     /home/andrew/.nerves/artifacts/nerves_system_bkln-portable-2.9.0
  app:        /home/andrew/nerves

|nerves_bootstrap| Loadpaths End
```

* Additional information about your host, target hardware or environment that might help

Custom target based on a beaglebone black.

Laptop is running Ubuntu 21.10.

**Additional context**
I took a quick look at where OneDHCPD was being started in vintage_net_direct, and it doesn't look like any options are passed in: https://github.com/nerves-networking/vintage_net_direct/blob/main/lib/vintage_net_direct.ex#L90

**Comment by aadavids** [comment]
I've opened up a PR with a fix that appears to work for me.

**Comment by fhunleth** [comment]
@aadavids Thanks for the issue and the PR. This really looks right and I'm slightly amazed that the fix was as simple as it was. I'm batching up vintage_net work for either the weekend or early next week. I'll double check and get a new release out with the fix.
